#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -N JE
#PBS -j oe
#PBS -q cluster.q
#PBS -V

DIR=/users/james/SSE
DIR2=lustre/sse

${DIR}/codes/reconstruct_signals ${DIR2}/results/reconstruction/recon_coefficients_100.dat ${DIR2}/results/wavelet/mean_and_rms_amplitude_combined.dat ${DIR2}/results/reconstruction/reconstructed_signals_100.dat ${DIR2}/results/reconstruction/infofile_recon_signals_100.dat

